// Flat-config ESLint setup. Next 16 will drop the legacy `next lint` shim
// entirely, so we go straight to the modern CLI form. Run via `npm run lint`.
//
// We extend the Next.js core-web-vitals + TypeScript presets exposed by
// eslint-config-next via FlatCompat, then layer on a handful of project
// rules. Kept intentionally small — the strict TypeScript settings in
// tsconfig.json already do the heavy lifting.
import { FlatCompat } from '@eslint/eslintrc';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // CLI / seed scripts are intentionally console-driven — they exist to
    // print diagnostics to stdout, not to feed structured logs.
    files: ['scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
  {
    rules: {
      // Don't shout about `_` prefixed unused params — that's our opt-out.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      // `any` is sometimes the right answer (Fawry/Supabase response shapes,
      // for instance) — warn instead of error so the build stays green while
      // we incrementally tighten.
      '@typescript-eslint/no-explicit-any': 'warn',
      // Loud about console.log in committed code — use lib/log instead.
      // Warn for warn/error/info so debugging scripts can still use them.
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      // RTL/i18n: catch most `<a href>` mistakes — Next.js wants Link.
      // Already in next/core-web-vitals, but keep noisy.
      '@next/next/no-html-link-for-pages': 'error',
    },
  },
  {
    // Mockups and seed scripts shouldn't drag the rest of the rules with them.
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'mockup1/**',
      'mockup4/**',
      'assets/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      // Auto-generated by Next.js — `next dev` rewrites it.
      'next-env.d.ts',
      // Standalone tsx test runners predate Vitest — keep them out of lint.
      'scripts/fawry-signature.test.ts',
      'scripts/fawry-webhook.test.ts',
    ],
  },
];
