// Language Toggle System for Infinity Bookstore
(function(){
  const translations = {
    ar: {
      // Navbar
      siteName: 'مكتبة إنفينيتي',
      siteNameSuffix: '| Infinity',
      home: 'الرئيسية',
      about: 'من نحن',
      books: 'الكتب',
      teachers: 'المدرسين',
      search: 'البحث',
      cart: 'السلة',
      wishlistNav: 'قائمة الأمنيات',
      login: 'تسجيل الدخول',

      // Homepage
      heroTitle: 'اكتشف أفضل الكتب التعليمية',
      heroSubtitle: 'مكتبتك الإلكترونية الأولى في مصر لكتب المدرسين التعليمية. احجز نسختك الآن واستلمها حتى باب بيتك.',
      browseBooks: 'تصفح الكتب',
      latestBooks: 'أحدث الكتب',
      latestBooksSubtitle: 'تصفح أحدث الكتب التعليمية من أفضل المدرسين',
      topTeachers: 'أفضل المدرسين',
      topTeachersSubtitle: 'تعرّف على أفضل المدرسين وكتبهم التعليمية',
      howToReserve: 'كيف تحجز كتابك؟',
      howToReserveSubtitle: 'أربع خطوات بسيطة للحصول على كتبك',
      step1Title: 'ابحث عن الكتاب',
      step1Desc: 'تصفح مكتبتنا الواسعة وابحث عن الكتب التي تحتاجها',
      step2Title: 'أضف للسلة',
      step2Desc: 'اختر الكتب المناسبة وأضفها إلى سلة مشترياتك',
      step3Title: 'أتمم الطلب',
      step3Desc: 'أدخل بيانات التوصيل واختر طريقة الدفع المناسبة',
      step4Title: 'استلم طلبك',
      step4Desc: 'نوصل طلبك لحد باب بيتك خلال ٢-٥ أيام عمل',
      testimonials: 'آراء طلابنا',
      testimonialsSubtitle: 'ماذا يقول طلابنا عن تجربتهم معنا',
      deliveryInfo: 'معلومات التوصيل',
      deliveryInfoSubtitle: 'نوصل لكل مكان في مصر',
      moreDelivery: 'المزيد عن التوصيل',

      // Category Carousel
      catSectionTitle: 'تصفح حسب التصنيف',
      catSectionSubtitle: 'اكتشف مجموعتنا المتنوعة من الكتب والمواد التعليمية',
      catBookWord: 'كتاب',
      catMath: 'الرياضيات',
      catMathCount: '٤٥',
      catPhysics: 'الفيزياء',
      catPhysicsCount: '٣٨',
      catChemistry: 'الكيمياء',
      catChemistryCount: '٣٢',
      catBiology: 'الأحياء',
      catBiologyCount: '٢٨',
      catArabic: 'اللغة العربية',
      catArabicCount: '٥٠',
      catEnglish: 'اللغة الإنجليزية',
      catEnglishCount: '٤٢',
      catHistory: 'التاريخ',
      catHistoryCount: '٢٠',
      catScience: 'العلوم',
      catScienceCount: '٣٥',

      // Category card link
      viewCatBooks: 'عرض الكتب',

      // New Arrivals Slider
      newArrivalsTitle: 'وصل حديثاً',
      newArrivalsSubtitle: 'أحدث الكتب المضافة لمكتبتنا',
      newBadge: 'جديد',
      newBook1Title: 'أساسيات الجبر الخطي',
      newBook1Author: 'أ/ كريم محمود',
      newBook1Price: '١٨٠ ج.م',
      newBook2Title: 'الفيزياء الحديثة',
      newBook2Author: 'أ/ هشام علي',
      newBook2Price: '٢٢٠ ج.م',
      newBook3Title: 'قواعد اللغة العربية',
      newBook3Author: 'أ/ فاطمة أحمد',
      newBook3Price: '١٥٠ ج.م',
      newBook4Title: 'الكيمياء العضوية',
      newBook4Author: 'أ/ سمير حسن',
      newBook4Price: '٢٠٠ ج.م',
      newBook5Title: 'تاريخ مصر المعاصر',
      newBook5Author: 'أ/ نادية محمد',
      newBook5Price: '١٧٠ ج.م',
      newBook6Title: 'أحياء الخلية',
      newBook6Author: 'أ/ منى السيد',
      newBook6Price: '١٩٠ ج.م',
      newBook7Title: 'English Grammar',
      newBook7Author: 'أ/ أمل يوسف',
      newBook7Price: '١٦٠ ج.م',
      newBook8Title: 'الجغرافيا الطبيعية',
      newBook8Author: 'أ/ عمرو خالد',
      newBook8Price: '١٤٠ ج.م',

      // Best Sellers Slider
      bestSellersTitle: 'الأكثر مبيعاً',
      bestSellersSubtitle: 'الكتب الأكثر طلباً من طلابنا',
      bestSellerBadge: 'الأكثر مبيعاً',
      soldText: 'تم بيع',
      copiesText: 'نسخة',
      bestBook1Title: 'الرياضيات للصف الثالث الثانوي',
      bestBook1Author: 'أ/ محمد السيد',
      bestBook1Price: '٢٥٠ ج.م',
      bestBook2Title: 'الفيزياء للصف الثالث الثانوي',
      bestBook2Author: 'أ/ أحمد عبدالله',
      bestBook2Price: '٢٣٠ ج.م',
      bestBook3Title: 'اللغة العربية الشاملة',
      bestBook3Author: 'أ/ سارة محمود',
      bestBook3Price: '٢٠٠ ج.م',
      bestBook4Title: 'الكيمياء المبسطة',
      bestBook4Author: 'أ/ حسام الدين',
      bestBook4Price: '٢١٠ ج.م',
      bestBook5Title: 'English Mastery',
      bestBook5Author: 'أ/ ريم عادل',
      bestBook5Price: '١٩٠ ج.م',
      bestBook6Title: 'الأحياء للمرحلة الثانوية',
      bestBook6Author: 'أ/ ياسمين حسن',
      bestBook6Price: '٢٢٠ ج.م',
      bestBook7Title: 'التفوق في الرياضيات',
      bestBook7Author: 'أ/ خالد إبراهيم',
      bestBook7Price: '٢٤٠ ج.م',
      bestBook8Title: 'أساسيات الفيزياء',
      bestBook8Author: 'أ/ طارق نور',
      bestBook8Price: '١٨٠ ج.م',

      // Badges
      newArrival: 'وصل حديثاً',
      bestSeller: 'الأكثر مبيعاً',

      // Book cards
      viewDetails: 'عرض التفاصيل',
      addToCart: 'أضف للسلة',
      reserveNow: 'احجز الآن',

      // Teachers
      viewProfile: 'عرض الملف الشخصي',
      viewBooks: 'عرض الكتب',
      booksCount: 'كتب متاحة',
      teacherBooksTitle: 'كتب المدرس',
      teacherReviews: 'آراء الطلاب عن المدرس',

      // Subjects
      math: 'رياضيات',
      physics: 'فيزياء',
      chemistry: 'كيمياء',
      biology: 'أحياء',
      arabic: 'عربي',
      english: 'إنجليزي',
      history: 'تاريخ',
      geography: 'جغرافيا',
      mathFull: 'الرياضيات',
      physicsFull: 'الفيزياء',
      chemistryFull: 'الكيمياء',
      biologyFull: 'الأحياء',
      arabicFull: 'اللغة العربية',
      englishFull: 'اللغة الإنجليزية',
      historyFull: 'التاريخ',
      geographyFull: 'الجغرافيا',

      // Books page
      allBooks: 'جميع الكتب',
      allBooksSubtitle: 'تصفح مجموعتنا الكاملة من الكتب التعليمية',
      allSubjects: 'كل المواد',
      allGrades: 'كل الصفوف',
      sortBy: 'ترتيب حسب',
      priceLow: 'السعر: الأقل أولاً',
      priceHigh: 'السعر: الأعلى أولاً',
      searchPlaceholder: 'ابحث عن كتاب...',
      grade1: 'الصف الأول الثانوي',
      grade2: 'الصف الثاني الثانوي',
      grade3: 'الصف الثالث الثانوي',

      // Book details
      bookDetailsTitle: 'تفاصيل الكتاب',
      studentReviews: 'تقييمات الطلاب',
      relatedBooks: 'كتب أخرى قد تعجبك',
      reviews: 'تقييم',
      pages: 'صفحة',
      edition: 'الطبعة',

      // Search
      searchHeroTitle: 'ابحث عن كتابك',
      searchInputPlaceholder: 'ابحث باسم الكتاب أو المدرس أو المادة...',
      all: 'الكل',
      showing: 'عرض',
      booksWord: 'كتب',
      noResults: 'لا توجد نتائج',
      noResultsHint: 'جرّب البحث بكلمات مختلفة أو تصفح جميع الكتب',

      // Cart
      shoppingCart: 'سلة المشتريات',
      orderSummary: 'ملخص الطلب',
      subtotal: 'المجموع الفرعي',
      deliveryFee: 'رسوم التوصيل',
      free: 'مجاناً',
      total: 'الإجمالي',
      checkout: 'إتمام الطلب',
      continueShopping: 'متابعة التسوق',
      emptyCart: 'سلتك فارغة',
      emptyCartMsg: 'لم تضف أي كتب إلى سلة المشتريات بعد',

      // Wishlist
      wishlist: 'قائمة الأمنيات',
      emptyWishlist: 'لا توجد كتب في قائمة أمنياتك',
      emptyWishlistMsg: 'أضف الكتب التي تعجبك لقائمة الأمنيات لتجدها بسهولة لاحقاً',

      // Login
      loginTitle: 'تسجيل الدخول',
      loginSubtitle: 'أهلاً بك مرة أخرى! سجل دخولك للمتابعة',
      emailOrPhone: 'البريد الإلكتروني أو رقم الهاتف',
      password: 'كلمة المرور',
      rememberMe: 'تذكرني',
      forgotPassword: 'نسيت كلمة المرور؟',
      or: 'أو',
      noAccount: 'ليس لديك حساب؟',
      registerNow: 'سجل الآن',

      // Register
      createAccount: 'إنشاء حساب جديد',
      registerSubtitle: 'انضم إلينا واستمتع بأفضل الكتب التعليمية',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف',
      confirmPassword: 'تأكيد كلمة المرور',
      gradeLevel: 'المرحلة الدراسية',
      selectGrade: 'اختر المرحلة الدراسية',
      graduate: 'خريج',
      parent: 'ولي أمر',
      createAccountBtn: 'إنشاء حساب',
      haveAccount: 'لديك حساب بالفعل؟',
      loginNow: 'سجل دخولك',
      enterFullName: 'أدخل اسمك الكامل',
      enterPassword: 'أدخل كلمة المرور',
      confirmPasswordPh: 'أعد إدخال كلمة المرور',

      // Grade level page
      gradeLevelBooks: 'كتب الصف الثالث الثانوي',
      gradeLevelSubtitle: 'جميع الكتب المتاحة للصف الثالث الثانوي مرتبة حسب المادة',

      // Delivery page
      deliveryPage: 'معلومات التوصيل والشحن',
      deliveryPageSubtitle: 'كل ما تحتاج معرفته عن خدمة التوصيل',
      fastDelivery: 'توصيل سريع وآمن',
      fastDeliveryDesc: 'نوصل طلبك لحد باب بيتك في أسرع وقت ممكن مع ضمان سلامة الكتب أثناء الشحن. جميع الطلبات يتم تغليفها بعناية.',
      deliveryGuarantee: 'ضمان الاستلام',
      deliveryGuaranteeDesc: 'في حالة عدم استلام الطلب أو وجود أي مشكلة، نضمن لك إعادة الأموال أو إعادة إرسال الطلب مجاناً.',
      deliveryAreas: 'مناطق التوصيل',
      deliveryAreasSubtitle: 'نغطي جميع محافظات مصر',
      greaterCairo: 'القاهرة الكبرى',
      alexandria: 'الإسكندرية',
      delta: 'الدلتا',
      upperEgypt: 'الصعيد',
      deliveryFees: 'رسوم التوصيل',
      orderValue: 'قيمة الطلب',
      deliveryFeeTh: 'رسوم التوصيل',
      notes: 'ملاحظات',
      trackOrder: 'تتبع طلبك',
      trackOrderDesc: 'أدخل رقم الطلب لمتابعة حالة الشحن',
      trackBtn: 'تتبع',
      trackPlaceholder: 'أدخل رقم الطلب مثال: INF-2026-001',
      freeDeliveryNote: 'توصيل مجاني لجميع المحافظات',
      fixedFeeNote: 'رسوم ثابتة لجميع المحافظات',
      moreThan500: 'أكثر من ٥٠٠ ج.م',
      range300to500: '٣٠٠ - ٥٠٠ ج.م',
      lessThan300: 'أقل من ٣٠٠ ج.م',
      fee30: '٣٠ ج.م',
      fee40: '٤٠ ج.م',
      cairoTime: '١-٢ يوم عمل',
      alexTime: '٢-٣ أيام عمل',
      deltaTime: '٣-٤ أيام عمل',
      upperTime: '٣-٥ أيام عمل',

      // FAQ
      faq: 'الأسئلة الشائعة',
      faqSubtitle: 'إجابات على أكثر الأسئلة شيوعاً',
      faqQ1: 'كيف أطلب كتاب من الموقع؟',
      faqA1: 'يمكنك تصفح الكتب من صفحة "الكتب" أو استخدام البحث للعثور على الكتاب المطلوب. اضغط على "أضف للسلة" ثم اذهب إلى سلة المشتريات لإتمام الطلب. أدخل بيانات التوصيل واختر طريقة الدفع.',
      faqQ2: 'ما هي طرق الدفع المتاحة؟',
      faqA2: 'نقبل الدفع عند الاستلام (كاش)، وكذلك الدفع الإلكتروني عبر فودافون كاش، اتصالات كاش، وأورانج كاش. كما نقبل التحويل البنكي والبطاقات الائتمانية.',
      faqQ3: 'كم تستغرق مدة التوصيل؟',
      faqA3: 'التوصيل للقاهرة والجيزة يستغرق ١-٢ يوم عمل. باقي المحافظات من ٢-٥ أيام عمل حسب المنطقة. يمكنك متابعة حالة طلبك من صفحة التوصيل.',
      faqQ4: 'هل يمكنني إرجاع الكتاب بعد الشراء؟',
      faqA4: 'نعم، يمكنك إرجاع الكتاب خلال ٧ أيام من الاستلام بشرط أن يكون في حالته الأصلية بدون أي كتابة أو تلف. سيتم رد المبلغ كاملاً بعد فحص الكتاب.',
      faqQ5: 'هل التوصيل مجاني؟',
      faqA5: 'التوصيل مجاني للطلبات التي تزيد قيمتها عن ٥٠٠ ج.م. الطلبات الأقل من ذلك تُضاف رسوم توصيل ٣٠-٤٠ ج.م حسب قيمة الطلب.',
      faqQ6: 'كيف أحجز كتاب قبل نزوله؟',
      faqA6: 'بعض الكتب تتيح خاصية الحجز المسبق. اضغط على "احجز الآن" في صفحة الكتاب وأدخل بياناتك. سنرسل لك إشعار عند توفر الكتاب وسنشحنه لك فوراً.',
      faqQ7: 'هل أحتاج حساب للشراء؟',
      faqA7: 'يُفضل إنشاء حساب لتتمكن من متابعة طلباتك وحفظ عناوين التوصيل. لكن يمكنك أيضاً الشراء كزائر بإدخال بياناتك مباشرة عند إتمام الطلب.',
      faqQ8: 'كيف أتواصل مع خدمة العملاء؟',
      faqA8: 'يمكنك التواصل معنا عبر واتساب على الرقم 01012345678، أو عبر البريد الإلكتروني info@infinity-books.com. فريق خدمة العملاء متاح يومياً من ٩ صباحاً حتى ٩ مساءً.',
      faqQ9: 'هل الكتب أصلية من المدرسين؟',
      faqA9: 'نعم، جميع الكتب المعروضة على مكتبة إنفينيتي أصلية ومن تأليف المدرسين مباشرة. نحن وكيل معتمد لجميع المدرسين المسجلين على الموقع.',
      faqQ10: 'هل يمكنني استبدال كتاب بآخر؟',
      faqA10: 'نعم، يمكنك استبدال الكتاب خلال ٧ أيام من الاستلام. تواصل مع خدمة العملاء وسنرتب عملية الاستبدال. قد تُطبق فروق أسعار في حالة اختلاف سعر الكتاب الجديد.',
      contactCta: 'لم تجد إجابة لسؤالك؟',
      contactCtaDesc: 'تواصل معنا وسنرد عليك في أقرب وقت',
      whatsapp: 'واتساب',
      emailBtn: 'بريد إلكتروني',

      // Footer
      footerAbout: 'مكتبة إنفينيتي',
      footerAboutDesc: 'مكتبتك الإلكترونية الأولى في مصر لكتب المدرسين التعليمية.',
      footerAboutDescFull: 'مكتبتك الإلكترونية الأولى في مصر لكتب المدرسين التعليمية. نوفر لك أفضل الكتب من أمهر المدرسين لجميع المراحل الدراسية.',
      quickLinks: 'روابط سريعة',
      subjects: 'المواد الدراسية',
      contactUs: 'تواصل معنا',
      footerHome: 'الرئيسية',
      footerAllBooks: 'جميع الكتب',
      footerTeachers: 'المدرسين',
      footerFaq: 'الأسئلة الشائعة',
      footerDelivery: 'معلومات التوصيل',
      footerMath: 'الرياضيات',
      footerPhysics: 'الفيزياء',
      footerChemistry: 'الكيمياء',
      footerBiology: 'الأحياء',
      footerArabic: 'اللغة العربية',
      footerEnglish: 'اللغة الإنجليزية',
      footerLocation: 'القاهرة، مصر',
      copyright: 'جميع الحقوق محفوظة \u00A9 2026 مكتبة إنفينيتي',

      // Delivery section on homepage
      deliveryAreasHome: 'مناطق التوصيل',
      deliveryAreasHomeDesc: 'نغطي جميع المحافظات',
      deliveryTime: 'مدة التوصيل',
      deliveryTimeVal: '٢-٥ أيام عمل',
      deliveryCairoTime: 'القاهرة والجيزة: ١-٢ يوم',
      deliveryFeeHome: 'رسوم التوصيل',
      deliveryFeeHomeVal: 'مجاناً للطلبات فوق ٥٠٠ ج.م',
      deliveryFeeHomeSub: 'أقل من ٥٠٠ ج.م: رسوم ٤٠ ج.م',

      // Testimonials
      testimonial1: '"الكتب ممتازة والشرح فيها واضح جداً. ساعدتني أحسن درجاتي في الرياضيات بشكل ملحوظ."',
      testimonial2: '"التوصيل سريع والكتب جودتها عالية. أنصح أي طالب يشتري منهم."',
      testimonial3: '"كتب الفيزياء بتاعة أستاذ أحمد غيرت مستوايا تماماً. شكراً مكتبة إنفينيتي!"',

      // Stationery
      stationery: 'الأدوات',
      stationeryTitle: 'الأدوات المدرسية',
      stationerySubtitle: 'كل ما يحتاجه الطالب من أدوات مدرسية بأفضل الأسعار',
      stationerySectionSubtitle: 'أدوات مدرسية متنوعة لجميع المراحل',
      stationeryAll: 'الكل',
      stationeryPens: 'أقلام',
      stationeryNotebooks: 'كراسات ودفاتر',
      stationeryBags: 'حقائب مدرسية',
      stationeryColors: 'ألوان وفرش',
      stationeryGeometry: 'أدوات هندسية',
      stationeryFolders: 'ملفات ومجلدات',
      stationeryCalculators: 'آلات حاسبة',
      viewAllStationery: 'عرض جميع الأدوات',
      footerStationery: 'الأدوات المدرسية',
      prod1Name: 'طقم أقلام جاف ملونة - ١٢ قلم',
      prod1Desc: 'طقم أقلام جاف بألوان متعددة مناسب للدراسة والتنظيم',
      prod2Name: 'قلم حبر باركر فضي',
      prod2Desc: 'قلم حبر أنيق من باركر بتصميم فضي كلاسيكي',
      prod3Name: 'كراسة ١٠٠ ورقة سلك',
      prod3Desc: 'كراسة سلك ١٠٠ ورقة مسطرة بغلاف مقوى',
      prod4Name: 'دفتر ملاحظات A5 جلد',
      prod4Desc: 'دفتر ملاحظات بغلاف جلدي فاخر مقاس A5',
      prod5Name: 'حقيبة مدرسية ظهر كبيرة',
      prod5Desc: 'حقيبة ظهر واسعة بجيوب متعددة ومبطنة للظهر',
      prod6Name: 'شنطة لاب توب ١٥ بوصة',
      prod6Desc: 'شنطة لاب توب مبطنة بحماية ضد الصدمات',
      prod7Name: 'علبة ألوان خشب ٢٤ لون',
      prod7Desc: 'ألوان خشبية عالية الجودة في علبة معدنية أنيقة',
      prod8Name: 'طقم ألوان مائية ١٢ لون',
      prod8Desc: 'طقم ألوان مائية احترافية مع فرشاة مجانية',
      prod9Name: 'طقم أدوات هندسية كامل',
      prod9Desc: 'طقم هندسي شامل: مسطرة، منقلة، فرجار، ومثلثات',
      prod10Name: 'مسطرة T شفافة ٣٠ سم',
      prod10Desc: 'مسطرة T شفافة من البلاستيك المقوى للرسم الهندسي',
      prod11Name: 'ملف بلاستيك ٤٠ جيب',
      prod11Desc: 'ملف بلاستيك شفاف ٤٠ جيب لتنظيم الأوراق والملزمات',
      prod12Name: 'آلة حاسبة علمية كاسيو',
      prod12Desc: 'آلة حاسبة علمية كاسيو بشاشة كبيرة و٢٤٠ وظيفة',

      // Stationery details
      customerReviews: 'تقييمات العملاء',
      similarProducts: 'منتجات مشابهة',
      addToWishlist: 'أضف للمفضلة',
      specBrand: 'العلامة التجارية',
      specColor: 'اللون',
      specMaterial: 'المادة',
      specWeight: 'الوزن',
      specOrigin: 'بلد المنشأ',
      quantity: 'الكمية',
      inStock: 'متوفر في المخزون',
      productSpecs: 'مواصفات المنتج',
      prod2DescFull: 'قلم حبر أنيق من باركر بتصميم فضي كلاسيكي. يتميز بسلاسة الكتابة وجودة الحبر العالية التي تدوم طويلاً. مثالي للاستخدام اليومي في المدرسة أو المكتب. يأتي في علبة هدايا فاخرة مما يجعله هدية مثالية للطلاب والمعلمين. مصنوع من الستانلس ستيل المقاوم للصدأ مع طلاء فضي لامع.',

      // Teachers page
      teachersTitle: 'المدرسين',
      teachersSubtitle: 'تعرّف على أفضل المدرسين وكتبهم التعليمية',
      booksCountNum1: '٣ كتب',
      booksCountNum2: '٢ كتب',
      booksCountNum3: '٢ كتب',
      booksCountNum4: '١ كتاب',
      booksCountNum5: '١ كتاب',
      booksCountNum6: '١ كتاب',

      // About page
      aboutHeroTitle: 'من نحن',
      aboutHeroSubtitle: 'تعرف على مكتبة إنفينيتي وقصتنا',
      ourStory: 'قصتنا',
      ourStorySubtitle: 'كيف بدأت مكتبة إنفينيتي',
      ourStoryHeading: 'من البداية إلى الآن',
      ourStoryP1: 'تأسست مكتبة إنفينيتي في عام ٢٠٢٠ بهدف توفير أفضل الكتب التعليمية للطلاب في جميع أنحاء مصر. بدأنا كمكتبة صغيرة في القاهرة، وبفضل ثقة عملائنا وجودة خدماتنا، توسعنا لنصبح واحدة من أبرز المكتبات التعليمية في المنطقة.',
      ourStoryP2: 'نؤمن بأن التعليم هو أساس بناء المستقبل، ولذلك نحرص على اختيار أفضل الكتب من أمهر المدرسين لنضعها بين يدي الطلاب بأسعار مناسبة.',
      visionMission: 'رؤيتنا ورسالتنا',
      visionMissionSubtitle: 'ما نسعى لتحقيقه',
      vision: 'الرؤية',
      visionText: 'أن نكون المكتبة التعليمية الأولى في مصر والوطن العربي، ونساهم في بناء جيل متعلم ومثقف.',
      mission: 'الرسالة',
      missionText: 'توفير كتب تعليمية عالية الجودة بأسعار مناسبة، مع تقديم تجربة تسوق سهلة وممتعة لجميع الطلاب وأولياء الأمور.',
      whyChooseUs: 'لماذا تختارنا؟',
      whyChooseUsSubtitle: 'ما يميز مكتبة إنفينيتي',
      feature1Title: 'كتب من أفضل المدرسين',
      feature1Desc: 'نوفر كتب تعليمية من أمهر وأفضل المدرسين في مصر',
      feature2Title: 'أسعار مناسبة للجميع',
      feature2Desc: 'أسعار تنافسية تناسب جميع الميزانيات',
      feature3Title: 'توصيل لجميع المحافظات',
      feature3Desc: 'نوصل طلبك لأي مكان في مصر بسرعة وأمان',
      feature4Title: 'خدمة عملاء متميزة',
      feature4Desc: 'فريق دعم متاح يومياً لمساعدتك في أي وقت',
      statsTitle: 'إنفينيتي بالأرقام',
      statBooks: 'كتاب متاح',
      statTeachers: 'مدرس',
      statStudents: 'طالب',
      statGovernorates: 'محافظة',
      ourTeam: 'فريق العمل',
      ourTeamSubtitle: 'تعرف على فريق عمل مكتبة إنفينيتي',
      teamMember1Name: 'أحمد محمد',
      teamMember1Role: 'المدير العام',
      teamMember2Name: 'سارة أحمد',
      teamMember2Role: 'مدير المبيعات',
      teamMember3Name: 'محمد حسن',
      teamMember3Role: 'خدمة العملاء',
      teamMember4Name: 'نور الدين',
      teamMember4Role: 'مدير التوصيل',
      aboutContactTitle: 'تواصل معنا',
      aboutContactSubtitle: 'هل لديك سؤال أو اقتراح؟ نحن هنا لمساعدتك',
      aboutPhone: 'الهاتف',
      aboutEmail: 'البريد الإلكتروني',
      aboutAddress: 'العنوان',
      aboutAddressVal: 'القاهرة، مصر',
      aboutWhatsappBtn: 'تواصل عبر واتساب',
    },
    en: {
      siteName: 'Infinity Bookstore',
      siteNameSuffix: '| Infinity',
      home: 'Home',
      about: 'About Us',
      books: 'Books',
      teachers: 'Teachers',
      search: 'Search',
      cart: 'Cart',
      wishlistNav: 'Wishlist',
      login: 'Login',

      heroTitle: 'Discover the Best Educational Books',
      heroSubtitle: 'Your first online bookstore in Egypt for educational teacher books. Reserve your copy now and get it delivered to your door.',
      browseBooks: 'Browse Books',
      latestBooks: 'Latest Books',
      latestBooksSubtitle: 'Browse the latest educational books from the best teachers',
      topTeachers: 'Top Teachers',
      topTeachersSubtitle: 'Meet the best teachers and their educational books',
      howToReserve: 'How to Reserve Your Book?',
      howToReserveSubtitle: 'Four simple steps to get your books',
      step1Title: 'Search for a Book',
      step1Desc: 'Browse our vast library and search for the books you need',
      step2Title: 'Add to Cart',
      step2Desc: 'Choose the right books and add them to your shopping cart',
      step3Title: 'Complete Order',
      step3Desc: 'Enter delivery details and choose the right payment method',
      step4Title: 'Receive Your Order',
      step4Desc: 'We deliver to your door within 2-5 business days',
      testimonials: 'Student Testimonials',
      testimonialsSubtitle: 'What our students say about their experience with us',
      deliveryInfo: 'Delivery Information',
      deliveryInfoSubtitle: 'We deliver everywhere in Egypt',
      moreDelivery: 'More about Delivery',

      // Category Carousel
      catSectionTitle: 'Browse by Category',
      catSectionSubtitle: 'Discover our diverse collection of books and educational materials',
      catBookWord: 'Books',
      catMath: 'Mathematics',
      catMathCount: '45',
      catPhysics: 'Physics',
      catPhysicsCount: '38',
      catChemistry: 'Chemistry',
      catChemistryCount: '32',
      catBiology: 'Biology',
      catBiologyCount: '28',
      catArabic: 'Arabic Language',
      catArabicCount: '50',
      catEnglish: 'English Language',
      catEnglishCount: '42',
      catHistory: 'History',
      catHistoryCount: '20',
      catScience: 'Science',
      catScienceCount: '35',

      // Category card link
      viewCatBooks: 'View Books',

      // New Arrivals Slider
      newArrivalsTitle: 'New Arrivals',
      newArrivalsSubtitle: 'Latest books added to our library',
      newBadge: 'New',
      newBook1Title: 'Linear Algebra Fundamentals',
      newBook1Author: 'Mr. Karim Mahmoud',
      newBook1Price: '180 EGP',
      newBook2Title: 'Modern Physics',
      newBook2Author: 'Mr. Hesham Ali',
      newBook2Price: '220 EGP',
      newBook3Title: 'Arabic Grammar Rules',
      newBook3Author: 'Ms. Fatma Ahmed',
      newBook3Price: '150 EGP',
      newBook4Title: 'Organic Chemistry',
      newBook4Author: 'Mr. Samir Hassan',
      newBook4Price: '200 EGP',
      newBook5Title: 'Modern Egyptian History',
      newBook5Author: 'Ms. Nadia Mohamed',
      newBook5Price: '170 EGP',
      newBook6Title: 'Cell Biology',
      newBook6Author: 'Ms. Mona El-Sayed',
      newBook6Price: '190 EGP',
      newBook7Title: 'English Grammar',
      newBook7Author: 'Ms. Amal Youssef',
      newBook7Price: '160 EGP',
      newBook8Title: 'Physical Geography',
      newBook8Author: 'Mr. Amr Khaled',
      newBook8Price: '140 EGP',

      // Best Sellers Slider
      bestSellersTitle: 'Best Sellers',
      bestSellersSubtitle: 'Most requested books by our students',
      bestSellerBadge: 'Best Seller',
      soldText: 'Sold',
      copiesText: 'copies',
      bestBook1Title: 'Mathematics for Grade 12',
      bestBook1Author: 'Mr. Mohamed El-Sayed',
      bestBook1Price: '250 EGP',
      bestBook2Title: 'Physics for Grade 12',
      bestBook2Author: 'Mr. Ahmed Abdullah',
      bestBook2Price: '230 EGP',
      bestBook3Title: 'Comprehensive Arabic',
      bestBook3Author: 'Ms. Sara Mahmoud',
      bestBook3Price: '200 EGP',
      bestBook4Title: 'Simplified Chemistry',
      bestBook4Author: 'Mr. Hossam El-Din',
      bestBook4Price: '210 EGP',
      bestBook5Title: 'English Mastery',
      bestBook5Author: 'Ms. Reem Adel',
      bestBook5Price: '190 EGP',
      bestBook6Title: 'Biology for High School',
      bestBook6Author: 'Ms. Yasmin Hassan',
      bestBook6Price: '220 EGP',
      bestBook7Title: 'Math Excellence',
      bestBook7Author: 'Mr. Khaled Ibrahim',
      bestBook7Price: '240 EGP',
      bestBook8Title: 'Physics Fundamentals',
      bestBook8Author: 'Mr. Tarek Nour',
      bestBook8Price: '180 EGP',

      newArrival: 'New Arrival',
      bestSeller: 'Best Seller',

      viewDetails: 'View Details',
      addToCart: 'Add to Cart',
      reserveNow: 'Reserve Now',

      viewProfile: 'View Profile',
      viewBooks: 'View Books',
      booksCount: 'Books Available',
      teacherBooksTitle: 'Teacher\'s Books',
      teacherReviews: 'Student Reviews about the Teacher',

      math: 'Mathematics',
      physics: 'Physics',
      chemistry: 'Chemistry',
      biology: 'Biology',
      arabic: 'Arabic',
      english: 'English',
      history: 'History',
      geography: 'Geography',
      mathFull: 'Mathematics',
      physicsFull: 'Physics',
      chemistryFull: 'Chemistry',
      biologyFull: 'Biology',
      arabicFull: 'Arabic Language',
      englishFull: 'English Language',
      historyFull: 'History',
      geographyFull: 'Geography',

      allBooks: 'All Books',
      allBooksSubtitle: 'Browse our full collection of educational books',
      allSubjects: 'All Subjects',
      allGrades: 'All Grades',
      sortBy: 'Sort By',
      priceLow: 'Price: Low to High',
      priceHigh: 'Price: High to Low',
      searchPlaceholder: 'Search for a book...',
      grade1: 'Grade 10',
      grade2: 'Grade 11',
      grade3: 'Grade 12',

      bookDetailsTitle: 'Book Details',
      studentReviews: 'Student Reviews',
      relatedBooks: 'You May Also Like',
      reviews: 'reviews',
      pages: 'pages',
      edition: 'Edition',

      searchHeroTitle: 'Search for Your Book',
      searchInputPlaceholder: 'Search by book name, teacher or subject...',
      all: 'All',
      showing: 'Showing',
      booksWord: 'books',
      noResults: 'No Results',
      noResultsHint: 'Try searching with different keywords or browse all books',

      shoppingCart: 'Shopping Cart',
      orderSummary: 'Order Summary',
      subtotal: 'Subtotal',
      deliveryFee: 'Delivery Fee',
      free: 'Free',
      total: 'Total',
      checkout: 'Checkout',
      continueShopping: 'Continue Shopping',
      emptyCart: 'Your cart is empty',
      emptyCartMsg: 'You haven\'t added any books to your cart yet',

      wishlist: 'Wishlist',
      emptyWishlist: 'No books in your wishlist',
      emptyWishlistMsg: 'Add books you like to your wishlist to find them easily later',

      loginTitle: 'Login',
      loginSubtitle: 'Welcome back! Log in to continue',
      emailOrPhone: 'Email or Phone Number',
      password: 'Password',
      rememberMe: 'Remember Me',
      forgotPassword: 'Forgot Password?',
      or: 'Or',
      noAccount: 'Don\'t have an account?',
      registerNow: 'Register Now',

      createAccount: 'Create New Account',
      registerSubtitle: 'Join us and enjoy the best educational books',
      fullName: 'Full Name',
      email: 'Email',
      phone: 'Phone Number',
      confirmPassword: 'Confirm Password',
      gradeLevel: 'Grade Level',
      selectGrade: 'Select Grade Level',
      graduate: 'Graduate',
      parent: 'Parent',
      createAccountBtn: 'Create Account',
      haveAccount: 'Already have an account?',
      loginNow: 'Log In',
      enterFullName: 'Enter your full name',
      enterPassword: 'Enter your password',
      confirmPasswordPh: 'Re-enter your password',

      gradeLevelBooks: 'Grade 12 Books',
      gradeLevelSubtitle: 'All available books for Grade 12 sorted by subject',

      deliveryPage: 'Delivery & Shipping Info',
      deliveryPageSubtitle: 'Everything you need to know about our delivery service',
      fastDelivery: 'Fast & Safe Delivery',
      fastDeliveryDesc: 'We deliver your order to your doorstep as fast as possible with guaranteed book safety during shipping. All orders are carefully packaged.',
      deliveryGuarantee: 'Delivery Guarantee',
      deliveryGuaranteeDesc: 'If you don\'t receive your order or there\'s any issue, we guarantee a full refund or free re-shipment.',
      deliveryAreas: 'Delivery Areas',
      deliveryAreasSubtitle: 'We cover all Egyptian governorates',
      greaterCairo: 'Greater Cairo',
      alexandria: 'Alexandria',
      delta: 'Delta',
      upperEgypt: 'Upper Egypt',
      deliveryFees: 'Delivery Fees',
      orderValue: 'Order Value',
      deliveryFeeTh: 'Delivery Fee',
      notes: 'Notes',
      trackOrder: 'Track Your Order',
      trackOrderDesc: 'Enter your order number to track shipping status',
      trackBtn: 'Track',
      trackPlaceholder: 'Enter order number e.g. INF-2026-001',
      freeDeliveryNote: 'Free delivery to all governorates',
      fixedFeeNote: 'Fixed fee for all governorates',
      moreThan500: 'More than 500 EGP',
      range300to500: '300 - 500 EGP',
      lessThan300: 'Less than 300 EGP',
      fee30: '30 EGP',
      fee40: '40 EGP',
      cairoTime: '1-2 business days',
      alexTime: '2-3 business days',
      deltaTime: '3-4 business days',
      upperTime: '3-5 business days',

      faq: 'FAQ',
      faqSubtitle: 'Answers to the most frequently asked questions',
      faqQ1: 'How do I order a book from the website?',
      faqA1: 'You can browse books from the "Books" page or use search to find the book you want. Click "Add to Cart" then go to your shopping cart to complete the order. Enter delivery details and choose your payment method.',
      faqQ2: 'What payment methods are available?',
      faqA2: 'We accept cash on delivery, as well as electronic payment via Vodafone Cash, Etisalat Cash, and Orange Cash. We also accept bank transfers and credit cards.',
      faqQ3: 'How long does delivery take?',
      faqA3: 'Delivery to Cairo and Giza takes 1-2 business days. Other governorates take 2-5 business days depending on the area. You can track your order from the delivery page.',
      faqQ4: 'Can I return a book after purchase?',
      faqA4: 'Yes, you can return a book within 7 days of receipt provided it is in its original condition without any writing or damage. The full amount will be refunded after inspection.',
      faqQ5: 'Is delivery free?',
      faqA5: 'Delivery is free for orders over 500 EGP. Orders below that have a delivery fee of 30-40 EGP depending on order value.',
      faqQ6: 'How do I pre-order a book?',
      faqA6: 'Some books offer pre-order. Click "Reserve Now" on the book page and enter your details. We\'ll notify you when the book is available and ship it immediately.',
      faqQ7: 'Do I need an account to purchase?',
      faqA7: 'It\'s recommended to create an account to track orders and save delivery addresses. However, you can also purchase as a guest by entering your details directly at checkout.',
      faqQ8: 'How do I contact customer service?',
      faqA8: 'You can contact us via WhatsApp at 01012345678, or by email at info@infinity-books.com. Our customer service team is available daily from 9 AM to 9 PM.',
      faqQ9: 'Are the books authentic from the teachers?',
      faqA9: 'Yes, all books displayed on Infinity Bookstore are authentic and authored directly by the teachers. We are an authorized agent for all registered teachers on the website.',
      faqQ10: 'Can I exchange a book for another?',
      faqA10: 'Yes, you can exchange a book within 7 days of receipt. Contact customer service and we\'ll arrange the exchange. Price differences may apply if the new book has a different price.',
      contactCta: 'Didn\'t find an answer?',
      contactCtaDesc: 'Contact us and we\'ll reply as soon as possible',
      whatsapp: 'WhatsApp',
      emailBtn: 'Email',

      footerAbout: 'Infinity Bookstore',
      footerAboutDesc: 'Your first online bookstore in Egypt for educational teacher books.',
      footerAboutDescFull: 'Your first online bookstore in Egypt for educational teacher books. We provide the best books from the most skilled teachers for all educational levels.',
      quickLinks: 'Quick Links',
      subjects: 'Subjects',
      contactUs: 'Contact Us',
      footerHome: 'Home',
      footerAllBooks: 'All Books',
      footerTeachers: 'Teachers',
      footerFaq: 'FAQ',
      footerDelivery: 'Delivery Info',
      footerMath: 'Mathematics',
      footerPhysics: 'Physics',
      footerChemistry: 'Chemistry',
      footerBiology: 'Biology',
      footerArabic: 'Arabic Language',
      footerEnglish: 'English Language',
      footerLocation: 'Cairo, Egypt',
      copyright: 'All Rights Reserved \u00A9 2026 Infinity Bookstore',

      deliveryAreasHome: 'Delivery Areas',
      deliveryAreasHomeDesc: 'We cover all governorates',
      deliveryTime: 'Delivery Time',
      deliveryTimeVal: '2-5 business days',
      deliveryCairoTime: 'Cairo & Giza: 1-2 days',
      deliveryFeeHome: 'Delivery Fee',
      deliveryFeeHomeVal: 'Free for orders above 500 EGP',
      deliveryFeeHomeSub: 'Under 500 EGP: 40 EGP fee',

      testimonial1: '"Excellent books with very clear explanations. They helped me improve my math grades significantly."',
      testimonial2: '"Fast delivery and high quality books. I recommend every student to buy from them."',
      testimonial3: '"Professor Ahmed\'s physics books completely changed my level. Thank you Infinity Bookstore!"',

      // Stationery
      stationery: 'Stationery',
      stationeryTitle: 'School Supplies',
      stationerySubtitle: 'Everything students need at the best prices',
      stationerySectionSubtitle: 'Various school supplies for all levels',
      stationeryAll: 'All',
      stationeryPens: 'Pens',
      stationeryNotebooks: 'Notebooks',
      stationeryBags: 'School Bags',
      stationeryColors: 'Colors & Brushes',
      stationeryGeometry: 'Geometry Tools',
      stationeryFolders: 'Files & Folders',
      stationeryCalculators: 'Calculators',
      viewAllStationery: 'View All Supplies',
      footerStationery: 'School Supplies',
      prod1Name: 'Colored Ballpoint Pen Set - 12 Pens',
      prod1Desc: 'Multi-color ballpoint pen set, perfect for studying and organizing',
      prod2Name: 'Parker Silver Ink Pen',
      prod2Desc: 'Elegant Parker ink pen with classic silver design',
      prod3Name: '100-Page Spiral Notebook',
      prod3Desc: '100-page lined spiral notebook with hardcover',
      prod4Name: 'A5 Leather Notebook',
      prod4Desc: 'Premium leather-bound notebook, A5 size',
      prod5Name: 'Large School Backpack',
      prod5Desc: 'Spacious backpack with multiple pockets and padded back',
      prod6Name: '15" Laptop Bag',
      prod6Desc: 'Padded laptop bag with shock protection',
      prod7Name: '24-Color Wooden Pencil Set',
      prod7Desc: 'High-quality wooden colored pencils in elegant metal case',
      prod8Name: '12-Color Watercolor Set',
      prod8Desc: 'Professional watercolor set with free brush',
      prod9Name: 'Complete Geometry Set',
      prod9Desc: 'Complete geometry set: ruler, protractor, compass, and triangles',
      prod10Name: '30cm Transparent T-Ruler',
      prod10Desc: 'Transparent reinforced plastic T-ruler for technical drawing',
      prod11Name: '40-Pocket Plastic Folder',
      prod11Desc: 'Clear plastic 40-pocket folder for organizing papers and handouts',
      prod12Name: 'Casio Scientific Calculator',
      prod12Desc: 'Casio scientific calculator with large display and 240 functions',

      // Stationery details
      customerReviews: 'Customer Reviews',
      similarProducts: 'Similar Products',
      addToWishlist: 'Add to Wishlist',
      specBrand: 'Brand',
      specColor: 'Color',
      specMaterial: 'Material',
      specWeight: 'Weight',
      specOrigin: 'Country of Origin',
      quantity: 'Quantity',
      inStock: 'In Stock',
      productSpecs: 'Product Specifications',
      prod2DescFull: 'An elegant Parker ink pen with a classic silver design. Features smooth writing and long-lasting high-quality ink. Perfect for daily use at school or the office. Comes in a premium gift box, making it an ideal gift for students and teachers. Made from rust-resistant stainless steel with a glossy silver finish.',

      // About page
      aboutHeroTitle: 'About Us',
      aboutHeroSubtitle: 'Learn about Infinity Bookstore and our story',
      ourStory: 'Our Story',
      ourStorySubtitle: 'How Infinity Bookstore started',
      ourStoryHeading: 'From the Beginning to Now',
      ourStoryP1: 'Infinity Bookstore was founded in 2020 with the goal of providing the best educational books for students across Egypt. We started as a small bookstore in Cairo, and thanks to our customers\' trust and quality of our services, we expanded to become one of the most prominent educational bookstores in the region.',
      ourStoryP2: 'We believe that education is the foundation of building the future, which is why we are committed to selecting the best books from the most skilled teachers to put them in students\' hands at affordable prices.',
      visionMission: 'Our Vision & Mission',
      visionMissionSubtitle: 'What we strive to achieve',
      vision: 'Vision',
      visionText: 'To be the leading educational bookstore in Egypt and the Arab world, contributing to building an educated and cultured generation.',
      mission: 'Mission',
      missionText: 'Providing high-quality educational books at affordable prices, while offering an easy and enjoyable shopping experience for all students and parents.',
      whyChooseUs: 'Why Choose Us?',
      whyChooseUsSubtitle: 'What makes Infinity Bookstore special',
      feature1Title: 'Books from Top Teachers',
      feature1Desc: 'We provide educational books from the most skilled and best teachers in Egypt',
      feature2Title: 'Affordable Prices for Everyone',
      feature2Desc: 'Competitive prices that suit all budgets',
      feature3Title: 'Delivery to All Governorates',
      feature3Desc: 'We deliver your order anywhere in Egypt quickly and safely',
      feature4Title: 'Excellent Customer Service',
      feature4Desc: 'A support team available daily to help you anytime',
      statsTitle: 'Infinity in Numbers',
      statBooks: 'Books Available',
      statTeachers: 'Teachers',
      statStudents: 'Students',
      statGovernorates: 'Governorates',
      ourTeam: 'Our Team',
      ourTeamSubtitle: 'Meet the Infinity Bookstore team',
      teamMember1Name: 'Ahmed Mohamed',
      teamMember1Role: 'General Manager',
      teamMember2Name: 'Sara Ahmed',
      teamMember2Role: 'Sales Manager',
      teamMember3Name: 'Mohamed Hassan',
      teamMember3Role: 'Customer Service',
      teamMember4Name: 'Nour El-Din',
      teamMember4Role: 'Delivery Manager',
      aboutContactTitle: 'Contact Us',
      aboutContactSubtitle: 'Have a question or suggestion? We are here to help',
      aboutPhone: 'Phone',
      aboutEmail: 'Email',
      aboutAddress: 'Address',
      aboutAddressVal: 'Cairo, Egypt',
      aboutWhatsappBtn: 'Chat on WhatsApp',

      teachersTitle: 'Teachers',
      teachersSubtitle: 'Meet the best teachers and their educational books',
      booksCountNum1: '3 books',
      booksCountNum2: '2 books',
      booksCountNum3: '2 books',
      booksCountNum4: '1 book',
      booksCountNum5: '1 book',
      booksCountNum6: '1 book',
    }
  };

  function applyLang(lang) {
    localStorage.setItem('lang', lang);
    const html = document.documentElement;
    html.lang = lang;
    html.dir = lang === 'ar' ? 'rtl' : 'ltr';

    // Update toggle button text
    const toggleBtn = document.getElementById('langToggleBtn');
    if (toggleBtn) {
      toggleBtn.textContent = lang === 'ar' ? 'EN' : 'عربي';
    }
    const toggleBtnMobile = document.getElementById('langToggleBtnMobile');
    if (toggleBtnMobile) {
      toggleBtnMobile.textContent = lang === 'ar' ? 'EN' : 'عربي';
    }

    // Apply translations to all data-i18n elements
    const t = translations[lang];
    document.querySelectorAll('[data-i18n]').forEach(function(el) {
      const key = el.getAttribute('data-i18n');
      if (t[key] !== undefined) {
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
          el.placeholder = t[key];
        } else if (el.tagName === 'OPTION') {
          el.textContent = t[key];
        } else {
          el.textContent = t[key];
        }
      }
    });

    // Handle data-i18n-placeholder separately
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) {
      const key = el.getAttribute('data-i18n-placeholder');
      if (t[key]) {
        el.placeholder = t[key];
      }
    });
  }

  function toggleLang() {
    var current = localStorage.getItem('lang') || 'ar';
    applyLang(current === 'ar' ? 'en' : 'ar');
  }

  // Expose globally
  window.toggleLang = toggleLang;
  window.applyLang = applyLang;

  // Auto-apply on DOM ready
  document.addEventListener('DOMContentLoaded', function() {
    var lang = localStorage.getItem('lang') || 'ar';
    applyLang(lang);
  });
})();
